[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  BUN_FLAGS = "--frozen-lockfile"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-1QWGMNC02K"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [".next/cache"]
